alertmanager:
  alertmanagerSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi
          storageClassName: efs-retain
  config:
    global:
      resolve_timeout: 5m
grafana:
  adminPassword: password123
  enabled: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: istio
      kubernetes.io/tls-acme: "true"
    enabled: true
    hosts:
      - {{ prometheus_domain }}
prometheus:
  prometheusSpec:
    retention: 10d
    scrapeInterval: 15s
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 10Gi
          storageClassName: efs-retain
