apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-retain
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ efs_id }}
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"