---
- name: Install AWS Load Balancer Controller and Istio
  hosts: bastion_host
  become: no
  vars_files:
    - ../vars.yml  # 프로젝트 루트 디렉토리에서 vars.yml 파일을 참조
  tasks:
    - name: Download IAM policy for AWS Load Balancer Controller
      become: yes
      get_url:
        url: https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.5.4/docs/install/iam_policy.json
        dest: "/tmp/iam_policy.json"

    - name: Check if IAM policy exists
      shell: aws iam list-policies --query "Policies[?PolicyName=='{{ policy_name }}'].[Arn]" --output text
      register: existing_policy
      ignore_errors: true

    - name: Create IAM policy if it does not exist
      shell: aws iam create-policy --policy-name {{ policy_name }} --policy-document file:///tmp/iam_policy.json
      register: policy_creation
      when: existing_policy.stdout == ""
      ignore_errors: true
      changed_when: "'PolicyArn' in policy_creation.stdout"

    - name: Set policy ARN
      set_fact:
        policy_arn: "{{ existing_policy.stdout if existing_policy.stdout != '' else policy_creation.stdout }}"

    - name: Create IAM service account for AWS Load Balancer Controller
      shell: |
        eksctl create iamserviceaccount \
          --region {{ region }} \
          --name aws-load-balancer-controller \
          --namespace kube-system \
          --cluster {{ cluster_name }} \
          --attach-policy-arn {{ policy_arn }} \
          --override-existing-serviceaccounts \
          --approve

    - name: Add EKS Helm repository
      shell: helm repo add eks https://aws.github.io/eks-charts
      args:
        executable: /bin/bash

    - name: Update Helm repositories
      shell: helm repo update
      args:
        executable: /bin/bash

    - name: Install AWS Load Balancer Controller using Helm
      shell: |
        helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
          --namespace kube-system \
          --set clusterName={{ cluster_name }} \
          --set serviceAccount.create=false \
          --set serviceAccount.name=aws-load-balancer-controller
      args:
        executable: /bin/bash

    - name: Add Istio Helm repository
      shell: helm repo add istio https://istio-release.storage.googleapis.com/charts
      args:
        executable: /bin/bash

    - name: Update Istio Helm repositories
      shell: helm repo update
      args:
        executable: /bin/bash

    - name: List Helm repositories
      shell: helm repo list
      args:
        executable: /bin/bash

    - name: Create Istio namespace
      shell: kubectl create namespace istio-system
      args:
        executable: /bin/bash

    - name: Install Istio Base using Helm
      shell: helm install istio-base istio/base -n istio-system
      args:
        executable: /bin/bash

    - name: Install Istiod using Helm
      shell: helm install istiod istio/istiod -n istio-system
      args:
        executable: /bin/bash
