---
- name: Install Helm and eksctl
  hosts: bastion_host
  become: yes
  tasks:
    - name: Download and install Helm
      block:
        - name: Download Helm install script
          get_url:
            url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            dest: /tmp/get_helm.sh
            mode: 0755

        - name: Execute Helm install script
          command: /tmp/get_helm.sh
          args:
            creates: /usr/local/bin/helm

        - name: Set Helm path in .bashrc
          lineinfile:
            path: ~/.bashrc
            line: 'export PATH=$PATH:/usr/local/bin'
            create: yes

        - name: Reload .bashrc
          shell: source ~/.bashrc
          args:
            executable: /bin/bash

    - name: Download and install eksctl
      block:
        - name: Download eksctl
          shell: curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp

        - name: Move eksctl to /usr/local/bin
          command: mv /tmp/eksctl /usr/local/bin/eksctl
          args:
            creates: /usr/local/bin/eksctl

        - name: Verify eksctl installation
          command: eksctl version
